# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161013_2047'),
        ('compare', '0009_mycategorytogoogletypes'),
        ('household', '0021_auto_20160925_0016'),
        ('account', '0002_fix_str'),
        ('capture', '0002_auto_20161012_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.MyBudgetCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='google_capture',
        ),
        migrations.DeleteModel(
            name='GooglePlaceType',
        ),
        migrations.DeleteModel(
            name='ExpenseItem',
        ),
        migrations.DeleteModel(
            name='GooglePlaceDetail',
        ),
        migrations.AddField(
            model_name='myexpenseitem',
            name='google_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GooglePlaceDetail'),
        ),
        migrations.AddField(
            model_name='myexpenseitem',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
        ),
        migrations.AddField(
            model_name='myexpenseitem',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
