# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_auto_20161016_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='myexpenseitem',
            name='expense_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
