# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_auto_20161209_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='receipts')),
                ('original_name', models.CharField(max_length=256)),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capture.MyExpenseItem')),
            ],
        ),
    ]
