# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0026_member_newsletter'),
        ('capture', '0007_myreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mynotetag',
            unique_together=set([('household', 'tag')]),
        ),
    ]
