# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0008_auto_20170509_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='myexpenseitem',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
