# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-11 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_auto_20161209_1846'),
        ('household', '0026_member_newsletter'),
        ('capture', '0009_myexpenseitem_reconciled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQuickAddCategoryAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_contains', models.CharField(max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.MyBudgetCategory')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household')),
            ],
        ),
        migrations.AddField(
            model_name='mynotetag',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='myquickaddcategoryassociation',
            unique_together=set([('household', 'payee_contains')]),
        ),
    ]
