# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-11 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0010_auto_20181111_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynotetag',
            old_name='default',
            new_name='is_default',
        ),
    ]
