# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ('title',)},
        ),
    ]
