# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20160903_1548'),
        ('account', '0002_fix_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_in_household', models.IntegerField()),
                ('oldest_birthyear', models.IntegerField()),
                ('opt_in_contribute', models.BooleanField(default=True)),
                ('paid_through', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_children', models.IntegerField()),
                ('grandchildren', models.BooleanField(default=True)),
                ('members_of_household', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('is_not_under_13', models.BooleanField(default=False)),
                ('owner', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_reference', models.CharField(max_length=128)),
                ('payment_last4_digits', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=20)),
                ('pet_type', models.CharField(max_length=20)),
                ('pet_breed', models.CharField(max_length=25)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.IntegerField()),
                ('fuel', models.CharField(max_length=10)),
                ('purchase_year', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finance', models.CharField(max_length=20)),
                ('gone_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RVHousehold',
            fields=[
                ('household_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='household.Household')),
                ('start_year', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IncomeType')),
                ('rig_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RigType')),
                ('use_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UseType')),
            ],
            bases=('household.household',),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleMake'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleModel'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='purchase_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehiclePurchaseType'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='statisfaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Satisfaction'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleStatus'),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleType'),
        ),
        migrations.AddField(
            model_name='householdpet',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
        ),
        migrations.AddField(
            model_name='householdpayment',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
        ),
        migrations.AddField(
            model_name='householdchildren',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
        ),
        migrations.AddField(
            model_name='household',
            name='budget_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BudgetModel'),
        ),
    ]
