# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmember',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
