# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_auto_20160903_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdchildren',
            name='household',
        ),
        migrations.RemoveField(
            model_name='householdpet',
            name='household',
        ),
        migrations.AddField(
            model_name='household',
            name='children',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='household',
            name='children_status',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='household',
            name='grandchildren',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='household',
            name='grandchildren_status',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='household',
            name='pets_cat',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='household',
            name='pets_dog',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='household',
            name='pets_other',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.DeleteModel(
            name='HouseholdChildren',
        ),
        migrations.DeleteModel(
            name='HouseholdPet',
        ),
    ]
