# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_auto_20160904_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='last_name',
        ),
    ]
