# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_auto_20160904_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='children',
        ),
        migrations.RemoveField(
            model_name='household',
            name='children_status',
        ),
        migrations.RemoveField(
            model_name='household',
            name='grandchildren',
        ),
        migrations.RemoveField(
            model_name='household',
            name='grandchildren_status',
        ),
        migrations.RemoveField(
            model_name='household',
            name='pets_cat',
        ),
        migrations.RemoveField(
            model_name='household',
            name='pets_dog',
        ),
        migrations.RemoveField(
            model_name='household',
            name='pets_other',
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='children',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='children_status',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='grandchildren',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='grandchildren_status',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='pets_cat',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='pets_dog',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='pets_other',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
