# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0006_auto_20160904_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvhousehold',
            name='indicate_children',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rvhousehold',
            name='indicate_pets',
            field=models.BooleanField(default=True),
        ),
    ]
