# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_auto_20160904_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvhousehold',
            name='indicate_children',
        ),
        migrations.RemoveField(
            model_name='rvhousehold',
            name='indicate_pets',
        ),
    ]
