# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0008_auto_20160904_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvhousehold',
            name='children_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rvhousehold',
            name='pets_answered',
            field=models.BooleanField(default=False),
        ),
    ]
