# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0009_auto_20160904_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmember',
            name='is_not_under_13',
        ),
        migrations.RemoveField(
            model_name='rvhousehold',
            name='children_answered',
        ),
        migrations.RemoveField(
            model_name='rvhousehold',
            name='pets_answered',
        ),
    ]
