# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0010_auto_20160905_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvhousehold',
            name='children_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='rvhousehold',
            name='grandchildren_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
