# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0013_auto_20160913_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseholdMember',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='HouseholdPayment',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
