# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0014_auto_20160913_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='opt_in_contribute',
            field=models.BooleanField(),
        ),
    ]
