# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0015_auto_20160915_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='statisfaction',
            new_name='satisfaction',
        ),
        migrations.AlterField(
            model_name='household',
            name='opt_in_contribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rvhousehold',
            name='children_status',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='rvhousehold',
            name='grandchildren_status',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='finance',
            field=models.IntegerField(),
        ),
    ]
