# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0018_auto_20160921_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
        ),
    ]
