# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0019_auto_20160921_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='finance',
            field=models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Gift'), (3, 'Loan - Bank'), (4, 'Loan - Dealer'), (5, 'Loan - Private')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.IntegerField(blank=True, choices=[(1, 'Diesel'), (2, 'Electric'), (3, 'Gasoline'), (4, 'Hybrid')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.VehicleMake'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.VehicleModel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.VehiclePurchaseType'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='satisfaction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Satisfaction'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.VehicleStatus'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.VehicleType'),
        ),
    ]
