# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0020_auto_20160922_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.IntegerField(blank=True, choices=[(1, 'Diesel'), (2, 'Electric'), (3, 'Gasoline'), (4, 'Hybrid'), (5, 'Not Applicable')]),
        ),
    ]
