# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0021_auto_20160925_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('security_code', models.CharField(blank=True, max_length=7, null=True)),
                ('invite_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('invite_household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household')),
            ],
        ),
    ]
