# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0023_auto_20161209_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
