# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0025_household_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
