# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0021_auto_20160925_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('annual', models.BooleanField(default=False)),
                ('annual_payment_month', models.IntegerField()),
                ('note', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyBudgetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_category_name', models.CharField(max_length=50)),
                ('category_perma_key', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyBudgetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_group_name', models.CharField(max_length=20)),
                ('group_description', models.TextField(default='description')),
                ('group_perma_key', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='household.Household')),
            ],
        ),
        migrations.AddField(
            model_name='mybudgetcategory',
            name='my_budget_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.MyBudgetGroup'),
        ),
        migrations.AddField(
            model_name='mybudgetcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.MyBudgetCategory'),
        ),
        migrations.AddField(
            model_name='mybudget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.MyBudgetCategory'),
        ),
    ]
