# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybudgetgroup',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='household.Household'),
            preserve_default=False,
        ),
    ]
