# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20160925_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybudgetcategory',
            name='category_perma_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mybudgetgroup',
            name='group_perma_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
