# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20160925_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybudgetgroup',
            name='group_list_order',
            field=models.IntegerField(default=0),
        ),
    ]
