# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_remove_mybudget_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybudget',
            name='effective_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
