# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_mybudget_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybudget',
            name='effective_date',
            field=models.DateField(auto_now=True),
        ),
    ]
