# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161013_2047'),
        ('compare', '0008_auto_20161012_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCategorytoGoogleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.MyBudgetCategory')),
                ('google_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GooglePlaceType')),
            ],
        ),
    ]
