# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160902_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig_item_type', models.CharField(max_length=32)),
                ('rig_item_type_description', models.TextField(default='description')),
            ],
        ),
        migrations.RenameModel(
            old_name='BugetModel',
            new_name='BudgetModel',
        ),
    ]
