# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160903_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfaction',
            name='satisfaction_index',
            field=models.IntegerField(),
        ),
    ]
