# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160903_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VehicleMake')),
            ],
        ),
        migrations.RenameModel(
            old_name='RigPurchaseType',
            new_name='VehiclePurchaseType',
        ),
        migrations.RenameModel(
            old_name='RigStatus',
            new_name='VehicleStatus',
        ),
        migrations.RenameModel(
            old_name='RigItemType',
            new_name='VehicleType',
        ),
        migrations.RemoveField(
            model_name='rigmodel',
            name='brand',
        ),
        migrations.RenameField(
            model_name='vehiclestatus',
            old_name='rig_status',
            new_name='vehicle_status',
        ),
        migrations.RenameField(
            model_name='vehiclestatus',
            old_name='rig_status_description',
            new_name='vehicle_status_description',
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='rig_item_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='rig_item_type_description',
            new_name='type_description',
        ),
        migrations.DeleteModel(
            name='RigBrand',
        ),
        migrations.DeleteModel(
            name='RigModel',
        ),
    ]
