# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160903_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('group_description', models.TextField(default='description')),
                ('budget_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BudgetModel')),
            ],
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='budget_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BudgetGroup'),
        ),
    ]
