# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_budgetcategory_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcategory',
            name='parent_category',
        ),
    ]
