# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_budgetcategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BudgetCategory'),
        ),
    ]
