# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_budgetcategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='category_perma_key',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='budgetgroup',
            name='group_perma_key',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BudgetCategory'),
        ),
    ]
