# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_budgetgroup_group_list_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='category_perma_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='budgetgroup',
            name='group_perma_key',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
