# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160925_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorytoGoogleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BudgetCategory')),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlaceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place_id', models.CharField(max_length=256)),
                ('place_name', models.CharField(max_length=256)),
                ('place_types', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='categorytogoogletypes',
            name='google_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GooglePlaceType'),
        ),
    ]
