# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161013_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemake',
            name='filter',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='filter',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
