# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161125_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleplacedetail',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='googleplacetype',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
